### ISSUE TITLE
Peoplefinder fails on login

### ISSUE THREAD

**Issue by glennblock** [aserto-demo/peoplefinder-acmecorp#32]
@ogazitt and I both verified this behavior. After deploying the app, I am getting the following error: AsertoClient: 'displayStateMap' caught exception TypeError: Channel credentials must be a ChannelCredentials object

Below is a screenshot in the app and Netlify logs

![Screenshot 2023-06-27 at 8 22 25 PM](https://github.com/aserto-demo/peoplefinder-acmecorp/assets/141124/1466ffdf-3c24-44cb-9e9b-891fa38280ce)

![Screenshot 2023-06-27 at 8 22 06 PM](https://github.com/aserto-demo/peoplefinder-acmecorp/assets/141124/6a03d58a-de63-4ccf-b609-c06ccea41494)

**Comment by ogazitt** [comment]
Resolved.
