### ISSUE TITLE
Changes to the policy do not appear to be getting picked up by the app

### ISSUE THREAD

**Issue by glennblock** [aserto-demo/peoplefinder-acmecorp#33]
I deployed to Netlify using the Console Quickstart feature. Then I went and wired up the Authorizer to connect to Github. I cloned my repo, and followed the peoplefinder [docs](https://docs.aserto.com/docs/getting-started/peoplefinder/modify-the-policy) to make policy changes to enable Managers to update their employees. I pushed the changes and tags and the updates show in the console, but they don't appear to propagate to the app. Per the docs, when I select Euan's boss April, I should see the "Update" button is enabled, which it is not as the screenshot shows.

![Screenshot 2023-06-28 at 2 57 14 PM](https://github.com/aserto-demo/peoplefinder-acmecorp/assets/141124/69f8bff6-2a67-4e90-a0bb-1fb712d6d5ae)
bled, but it is not.

![Screenshot 2023-06-28 at 2 57 48 PM](https://github.com/aserto-demo/peoplefinder-acmecorp/assets/141124/f8412e7d-ef03-4052-82d3-d9281805a71b)

![Screenshot 2023-06-28 at 2 58 06 PM](https://github.com/aserto-demo/peoplefinder-acmecorp/assets/141124/d902cfa7-df24-4402-b72c-12a5ccf97acc)

![Screenshot 2023-06-28 at 2 58 17 PM](https://github.com/aserto-demo/peoplefinder-acmecorp/assets/141124/9ddef0e1-95a1-4985-bca8-7da3f28c6b6b)

![Screenshot 2023-06-28 at 3 01 52 PM](https://github.com/aserto-demo/peoplefinder-acmecorp/assets/141124/56b507da-0e71-4b24-a91a-0f0f0797a293)

I tried forcing the app to redeploy and it did not make a difference. Is there something I am missing?

**Comment by ogazitt** [comment]
Addressed last year.
